Repository wyncode/C36_midterm_carolina_elias_rene_tristan, pull requests merged in 2020-02, with the labels that each got.

#4 Static API data added to backend
  Animaldata.json
  client/src/App.jsx
  package.json
  server.js
  yarn.lock
Labels: enhancement

#13 made nav bar static by using className and Link to
  client/src/App.css
  client/src/App.jsx
  client/src/Components/Nav.jsx
  client/src/Components/Pets.js
Labels: enhancement

#20 only display pet posts that include pictures
  client/src/Components/Cards.js
Labels: enhancement

#25 Filtered only cats and dogs so team can work on the rest of the animals
  client/src/Components/Cats.js
  client/src/Components/Dogs.js
Labels: enhancement

#28 Filter by agegroups
  client/src/Components/Cards.js
  client/src/Components/Cats.js
  client/src/Components/Dogs.js
Labels: enhancement

#30 basic filters for age, size, and gender
  client/src/Components/About.js
  client/src/Components/Cards.js
  client/src/Components/Pets 2.js
Labels: enhancement

#33 added Home back to router
  client/src/App.jsx
Labels: bug

#35 adding filters again because they all disappeared
  client/src/Components/Cards.js
  client/src/Components/Dogs.js
Labels: bug

#43 Added our personal sentences to the about me page
  client/src/Components/About.js
  client/src/Components/Cards.js
  client/src/Components/Pet_Components/Birds.js
  client/src/Components/Pet_Components/Ferrets.js
  client/src/Components/Pet_Components/Fish.js
  client/src/Components/Pet_Components/Rabbits.js
  client/src/Components/Pet_Components/Reptiles.js
  client/src/Components/Pet_Components/Rodents.js
Labels: enhancement

#37 Server API call Fix
  server.js
Labels: enhancement

#49 fully functional filters without styling
  client/src/Components/Cards.js
  client/src/Components/Pet_Components/Birds.js
  client/src/Components/Pet_Components/Cats.js
  client/src/Components/Pet_Components/Dogs.js
  client/src/Components/filter.js
Labels: enhancement

#51 Tristan's token server API token server fetch fixx
  client/src/Components/Cards.js
  server.js
Labels: enhancement

#55 Fix the api not pulling size
  server.js
Labels: bug

#65 Tristan created new api request for animal types, and filters are n…
  client/src/App.jsx
  client/src/Components/AdoptMe.js
  client/src/Components/AnimalList.js
  client/src/Components/Cards.js
  client/src/Components/Nav.jsx
  client/src/Components/Pet.js
  client/src/Components/PetDetail.js
  client/src/Components/Pet_Components/Birds.js
  client/src/Components/Pet_Components/Cats.js
  client/src/Components/Pet_Components/Dogs.js
  client/src/Components/Pet_Components/Ferrets.js
  client/src/Components/Pet_Components/Fish.js
  client/src/Components/Pet_Components/Rabbits.js
  client/src/Components/Pet_Components/Reptiles.js
  client/src/Components/Pet_Components/Rodents.js
  client/src/Components/Pets 2.js
  client/src/Components/Pets.js
  server.js
  utilities.js
Labels: enhancement

#67 fixed the carousel routes
  client/src/Components/Carousel.js
Labels: bug

#69 fixing naming conventions for routes
  client/src/Components/Carousel.js
Labels: bug

#70 Fixes issue with cards and brings back more filtering options
  client/src/Components/Cards.js
Labels: bug, enhancement

#76 navbar options reduced due to API data limitations
  client/src/Components/Nav.jsx
Labels: enhancement

#79 removed the .link from the nav.links in nav.jsx
  client/src/Components/Nav.jsx
  client/src/Components/filter.js
Labels: enhancement

#87 bug fixed
  client/package.json
  client/src/Components/Cards.js
  client/src/Components/Nav.jsx
  client/src/Components/PetDetail.js
  client/yarn.lock
Labels: bug

#90 re submitting rene's styling due to github issue
  client/package.json
  client/src/Animation/animation.jsx
  client/src/Components/Pet.js
  client/yarn.lock
Labels: enhancement

#93 no more warninig in console
  client/src/App.jsx
  client/src/Components/About.js
  client/src/Components/Cards.js
  client/src/Components/Home.js
  client/src/Components/HomeBanner.js
  client/src/Components/Nav.jsx
  client/src/Components/PetDetail.js
Labels: bug
